### ISSUE TITLE
End to End test improvements

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#1797]
### additional testing

We now have a single end-to-end test in our test suite. There's plenty of ways we can improve upon it:

- [x] nodemailer has DKIM signing support, so enable that + haraka's dkim_verify plugin, and verify the DKIM signature on the test email.  #2026 
- [x] upgrade to nodemailer 3 (or not?) #2026 
    - update: nodemailer 3 is node v6+ only
- [x] enable an AUTH plugin and send an email with AUTH credentials #2026
    - [x] make sure invalid credentials fail to auth #2026 
- [ ] tls: SNI & cert validity tests
- [ ] spin up two Haraka instances and test outbound.
- [x] send an email using smtp_client.js

**Comment by baudehlo** [comment]
Add: spin up two Haraka instances and test outbound.
